config/routes.rb
MauiMine::Application.routes.draw do
  resources :resources, only: [:index, :destroy]

  match 'manage/:id' => 'resources#manage'
  match 'manage' => 'resources#manage'

  root to: 'resources#manage'

end

app/models/location.rb
class Location < ActiveRecord::Base

  class Region < Struct.new(:id, :name, :zip)
  end

  REGIONS = [
      Region.new(1, 'All', nil),
      Region.new(2, 'Hana', 96713),
      Region.new(3, 'Haiku', 96708),
      Region.new(4, 'Kihei', 96753),
      Region.new(5, 'Kahului', 96732),
      Region.new(6, 'Kaanapali', 96761),
      Region.new(7, 'Kaupo', 96790),
      Region.new(8, 'Wailuku', 96793),
      Region.new(9, 'Waiehu', 96793),
      Region.new(10, 'Waihee', 96793),
      Region.new(11, 'Napili', 96761),
      Region.new(12, 'Central', nil),
      Region.new(13, 'Wailea', 96753)
  ]

  attr_accessible :address,
                  :address2,
                  :state,
                  :zip,
                  :region_id,
                  :latitude,
                  :longitude

  has_many :resources

  validates :address, presence: true

  before_validation :set_zip_from_region

  def region
    REGIONS.find { |rn| rn.id == region_id }
  end

  def label
    "#{address} #{region.try(:name)}"
  end

  def coords_set?
    latitude.present? && longitude.present?
  end

  def set_coords(coords)
    write_attribute(:latitude, coords[:latitude])
    write_attribute(:longitude, coords[:longitude])
  end

  class << self
    def coords
      [:latitude, :longitude]
    end
  end

  #
  # Private
  #

  private


  def set_zip_from_region
    write_attribute(:zip, region.zip) if region
  end

end

app/models/resource.rb
class Resource < ActiveRecord::Base
  attr_accessible :location_id, :name, :url

  attr_accessor :add_coordinates, :add_location

  belongs_to :location

  validates :name, presence: true
  validates :url, uniqueness: true, allow_blank: true

  before_validation :strip_protocol

  acts_as_ordered_taggable

  private

  def strip_protocol
    url.gsub!(%r{\Ahttp://|/\z}, '') if url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  before_filter :set_tags, except: :destroy

  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resources }
    end
  end

  #  =Manage
  # Result of combining #new #edit #update #create
  # * /manage/:id(.format)
  # * /manage(.:format)
  def manage
    @resource = Resource.where(id: params[:id]).first_or_initialize

    # set flags for check boxes - GET
    @resource.add_coordinates = @resource.location && @resource.location.coords_set?
    @resource.add_location = !(@resource.location || @resource.build_location).new_record?

    if request.post? || request.put?
      @resource.transaction do
        r_param = params[:resource]
        l_param = r_param[:location]

        # set flags from check boxes
        @resource.add_location = r_param[:add_location] != '0'
        @resource.add_coordinates = r_param[:add_coordinates] != '0'

        # set resource attributes
        @resource.name = r_param[:name]
        @resource.url = r_param[:url]

        # save tags
        @resource.tag_list = r_param[:tag_list]

        if @resource.add_location
          l_param = l_param.except(*Location.coords) unless @resource.add_coordinates

          @resource.location = Location.find_or_initialize_by_address_and_region_id(l_param[:address], l_param[:region_id])
          @resource.location.state = 'HI'
          @resource.location.set_coords(l_param)
          @resource.location.save!
        else
          @resource.location.try(:destroy) unless Resource.find_all_by_location_id(@resource.location.try(:id))
          @resource.location = nil
        end

        @resource.save!
        redirect_to(resources_path, notice: "#{@resource.name} was saved")
      end
    end
  rescue
    request.flash[:alert] = "Try again, minus the errors. #{@resource.errors.full_messages.first}"
  end

  # DELETE /resources/1
  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy

    redirect_to(resources_path, notice: "#{@resource.name} was deleted")
  end

  private

  def set_tags
    @tags ||= ActsAsTaggableOn::Tag.all.map(&:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALERT_TYPES = [:error, :info, :success, :warning]

  def my_bootstrap_flash
    flash_messages = []
    flash.discard.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = :success if type == :notice
      type = :error if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                               msg, :class => "alert fade in alert-#{type}")
        flash_messages << text if message
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MauiMine" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">MauiMine</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "List", resources_path  %></li>
              <li><%= link_to "New Resource", manage_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="">
          <%= my_bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource, url: manage_path(id: @resource), html: {:class => 'form-horizontal resources'}) do |f| %>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :url, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :url, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label(:tag_list, :class => 'control-label') %>
      <div class="controls">
        <%= f.hidden_field(:tag_list, class: 'select2-offscreen', id: 'tags_field', style: 'width:92%;') %>
      </div>
    </div>
    <%= content_tag(:div, class: 'toggle-resource-location') do %>
        <%= f.fields_for(:location, @resource.location) do |lf| %>
            <div class="control-group">
              <%= lf.label(:address, 'Location', class: 'control-label') %>
              <div class="controls">
                <%= lf.text_field(:address, class: 'text_field') %>
              </div>
            </div>
            <div class="control-group">
              <%= lf.label(:region_id, class: 'control-label') %>
              <div class="controls">
                <%= lf.select(:region_id, Location::REGIONS.map { |x| [x.name, x.id] }, class: 'text_field') %>
              </div>
            </div>
        <% end %>
        <div class="coordinates">
          <%= f.fields_for(:location, @resource.location) do |lf| %>
              <div class="control-group">
                <%= lf.label :latitude, :class => 'control-label' %>
                <div class="controls">
                  <%= lf.text_field :latitude, :class => 'text_field' %>
                </div>
              </div>
              <div class="control-group">
                <%= lf.label :longitude, :class => 'control-label' %>
                <div class="controls">
                  <%= lf.text_field :longitude, :class => 'text_field' %>
                </div>
              </div>
          <% end %>
        </div>
    <% end %>

    <div class="form-actions" style="margin-top: 0;padding-top: 10px;padding-bottom: 10px;">
      <div id="submit_control">
        <%= f.submit nil, :class => 'btn btn-primary' %>
      </div>
      <div id="add_loc" class="toggle-button">
        <%= f.check_box(:add_location) %>
      </div>
      <div id="coords_control">
        <span id="add_coords" class="toggle-button">
          <%= f.check_box(:add_coordinates) %>
        </span>
      </div>
    </div>
<% end %>
<%= hidden_field_tag(:tag_data, @tags.join(',')) %>

app/views/resources/index.html.erb
<% model_class = Resource %>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:url) %></th>
    <th><%= model_class.human_attribute_name(:tags) %></th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= link_to(resource.url, "http://#{resource.url}", target: '_blank') if resource.url %></td>
        <td><%= resource.tag_list %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      manage_path(id: resource), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      resource_path(resource),
                      :method => :delete,
                      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/resources/manage.html.erb
<%= render 'form' %>